version: 0.2

env:
  variables:
    TOMCAT_SERVER_IP: "54.90.200.46"
    TOMCAT_USER: "admin"
    TOMCAT_PASSWORD: "Rajesh@123"
    SONARQUBE_PROJECT_KEY: "Inventory.io"
    SONARQUBE_SERVER: "http://54.159.232.17:9000"
    SONARQUBE_TOKEN: "sqp_5e6bf93ee8c5bc90bb8d200a87175084f1c0ffa5"
    S3_BUCKET: "project-capstone"

phases:
  install:
    commands:
      - echo AWS CLI is already installed in the standard image
      - echo Maven is already installed in the standard image
      - echo Installing SonarQube Scanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
      - sonar-scanner --version

  pre_build:
    commands:
      - echo Validating project...
      - mvn validate -X
      - echo Compiling the project...
      - mvn compile
      - echo Running tests...
      - mvn test
      - echo Building the package with Maven...
      - mvn package
      - echo Running SonarQube analysis...
      - sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.host.url=$SONARQUBE_SERVER -Dsonar.login=$SONARQUBE_TOKEN

  build:
    commands:
      - echo Deploying the WAR artifact to remote Maven repository...
      - mvn deploy -DaltDeploymentRepository=release::default::s3://$S3_BUCKET/release/
      - echo Uploading the WAR artifact to S3...
      - export WAR_FILE=$(ls target/*.war)
      - echo "WAR file is $WAR_FILE"
      - aws s3 cp $WAR_FILE s3://$S3_BUCKET/artifacts/

  post_build:
    commands:
      - echo Checking SonarQube quality gate status...
      - curl -u $SONARQUBE_TOKEN:"$SONARQUBE_SERVER/api/qualitygates/project_status?projectKey=$SONARQUBE_PROJECT_KEY" | jq '.projectStatus.status'
      - echo Deploying the WAR file to Tomcat...
      - aws s3 cp s3://$S3_BUCKET/artifacts/$(basename $WAR_FILE) /opt/tomcat/temp/
      - sudo mv /opt/tomcat/temp/$(basename $WAR_FILE) /opt/tomcat/webapps/
      - echo Restarting Tomcat...
      - sudo systemctl restart tomcat  # Use 'service tomcat restart' for older versions

artifacts:
  files:
    - target/*.war
