version: 0.2

env:
  variables:
    TOMCAT_SERVER_IP: "34.229.122.153"
    TOMCAT_USER: "admin"
    TOMCAT_PASSWORD: "Rajesh@123"
    SONARQUBE_PROJECT_KEY: "Inventory.io"
    SONARQUBE_SERVER: "http://3.88.53.158:9000"
    SONARQUBE_TOKEN: "sqp_5e6bf93ee8c5bc90bb8d200a87175084f1c0ffa5"
    CODEARTIFACT_SECRET_ID: "secrete-key"  # Secret ID in Secrets Manager

phases:
  install:
    commands:
      - echo AWS CLI is already installed in the standard image
      - echo Maven is already installed in the standard image
      - echo Installing SonarQube Scanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
      - sonar-scanner --version

  pre_build:
    commands:
      - echo Fetching CodeArtifact auth token from Secrets Manager...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws secretsmanager get-secret-value --secret-id $CODEARTIFACT_SECRET_ID --query 'SecretString' --output text | jq -r '.CODEARTIFACT_AUTH_TOKEN')
      - echo Validating project...
      - mvn validate
      - echo Compiling the project...
      - mvn compile
      - echo Running tests...
      - mvn test
      - echo Building the package with Maven...
      - mvn package
      - echo Running SonarQube analysis...
      - sonar-scanner -Dsonar.projectKey=Inventory.io -Dsonar.host.url=http://3.88.53.158:9000 -Dsonar.login=sqp_5e6bf93ee8c5bc90bb8d200a87175084f1c0ffa5
  build:
    commands:
      - echo Deploying the WAR artifact to CodeArtifact...
      - mvn deploy
      - echo Uploading the WAR artifact to CodeArtifact...
      - aws codeartifact put-package-version --domain capstone --domain-owner <domain-owner-id> --repository capstone_project --package inventory --package-version 1.0.0 --file target/*.war

  post_build:
    commands:
      - echo Checking SonarQube quality gate status...
      - curl -u $SONARQUBE_TOKEN:"$SONARQUBE_SERVER/api/qualitygates/project_status?projectKey=$SONARQUBE_PROJECT_KEY" | jq '.projectStatus.status'
      - echo Deploying the WAR file to Tomcat...
      - aws s3 cp s3://$S3_BUCKET/artifacts/*.war /opt/tomcat/temp/
      - sudo mv /opt/tomcat/temp/*.war /opt/tomcat/webapps/
      - echo Restarting Tomcat...
      - sudo systemctl restart tomcat  # Use 'service tomcat restart' for older versions

artifacts:
  files:
    - target/*.war
